export const environment = {
  production: true,
  apiUrl: 'https://api.hospitalityos.com/api',
  authApiUrl: 'https://api.hospitalityos.com/api/v1/auth',
  organizationApiUrl: 'https://api.hospitalityos.com/api/v1/organization',
  hotelsApiUrl: 'https://api.hospitalityos.com/api/v1/hotels',
  roomsApiUrl: 'https://api.hospitalityos.com/api/v1/rooms',
  reservationsApiUrl: 'https://api.hospitalityos.com/api/v1/reservations',
  guestsApiUrl: 'https://api.hospitalityos.com/api/v1/guests',
  financeApiUrl: 'https://api.hospitalityos.com/api/v1/finance',
  ratesApiUrl: 'https://api.hospitalityos.com/api/v1/rates',
  channelsApiUrl: 'https://api.hospitalityos.com/api/v1/channels',
  onboardingApiUrl: 'https://api.hospitalityos.com/api/v1/onboarding',
  widgetApiUrl: 'https://api.hospitalityos.com/api/v1/public/widget',
  paymentsApiUrl: 'https://api.hospitalityos.com/api/v1/public/payments',
  ratePlansApiUrl: 'https://api.hospitalityos.com/api/v1/rate-plans',
  dashboardApiUrl: 'https://api.hospitalityos.com/api/v1/dashboard',
  auditApiUrl: 'https://api.hospitalityos.com/api/v1/audit',
  automationApiUrl: 'https://api.hospitalityos.com/api/v1/workflows',
  messagesApiUrl: 'https://api.hospitalityos.com/api/v1/messages',
  appName: 'HospitalityOS',
  version: '1.0.0',
  debug: false
};